export const packageJson = {
  name: "",
  version: "",
  dependencies: {
    "@bentley/icons-generic": "^1.0.13",
    "@itwin/core-telemetry": "^3.1.0-dev.42",
    "@itwin/appui-abstract": "^3.1.0-dev.42",
    "@itwin/appui-layout-react": "^3.1.0-dev.42",
    "@itwin/appui-react": "^3.1.0-dev.42",
    "@itwin/browser-authorization": "^0.5.1",
    "@itwin/components-react": "^3.1.0-dev.42",
    "@itwin/core-bentley": "^3.1.0-dev.42",
    "@itwin/core-common": "^3.1.0-dev.42",
    "@itwin/core-frontend": "^3.1.0-dev.42",
    "@itwin/core-geometry": "^3.1.0-dev.42",
    "@itwin/core-i18n": "^3.1.0-dev.42",
    "@itwin/core-markup": "^3.1.0-dev.42",
    "@itwin/core-orbitgt": "^3.1.0-dev.42",
    "@itwin/core-quantity": "^3.1.0-dev.42",
    "@itwin/core-react": "^3.1.0-dev.42",
    "@itwin/imodel-components-react": "^3.1.0-dev.42",
    "@itwin/imodels-access-frontend": "^1.0.1",
    "@itwin/imodels-client-management": "^1.0.1",
    "@itwin/itwinui-react": "^1.16.2",
    "@itwin/presentation-common": "^3.1.0-dev.42",
    "@itwin/presentation-frontend": "^3.1.0-dev.42",
    "@itwin/reality-data-client": "^0.7.0",
    "@itwin/web-viewer-react": "^2.0.0",
    "@itwin/webgl-compatibility": "^3.1.0-dev.42",
    history: "^4.10.1",
    react: "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.0",
  },
  devDependencies: {
    "@itwin/eslint-plugin": "^3.0.2",
    "@testing-library/react": "^12.1.4",
    "@types/jest": "^27.4.1",
    "@types/history": "^4.7.6",
    "@types/node": "^14.0.19",
    "@types/react": "^17.0.9",
    "@types/react-dom": "^17.0.9",
    eslint: "^7.11.0",
    jest: "^27.5.1",
    typescript: "~4.4.0",
  },
  eslintConfig: {
    plugins: ["@itwin"],
    extends: "plugin:@itwin/itwinjs-recommended",
  },
  scripts: {
    start: "",
    build: "",
    test: "",
  },
  browserslist: [
    "last 4 chrome version",
    "last 4 firefox version",
    "last 4 safari version",
    "last 4 ios version",
    "last 4 ChromeAndroid version",
    "last 4 edge version",
    "not dead",
    "not <0.2%",
  ],
};
