# This workflow will install dependencies, build the monorepo, and publish packages from the "next" branch as prereleases
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: iTwin Viewer NPM Publish from Next branch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUBLISH_PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          set -e
          echo 'Installing...'
          node common/scripts/install-run-rush.js install
          echo 'Building...'
          node common/scripts/install-run-rush.js rebuild
          echo 'Publishing...'
          git config user.name "iTwinViewerWorkflow"
          git config user.email "itwinviewer@users.noreply.github.com"
          node common/scripts/install-run-rush.js version --bump --target-branch next
          node common/scripts/install-run-rush.js publish --include-all --version-policy prerelease-monorepo-lockStep --set-access-level public --apply --publish --npm-auth-token $NPM_TOKEN --target-branch next --tag next
        env:
          NPM_TOKEN: ${{ secrets.NPMJS_PUBLISH_ITWIN }}
